# This workflow will do a clean install of node dependencies, cache/restore them and build the source code
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  node-version: '14'

jobs:
  Build:
    name: Build server application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build --if-present

  Test:
    name: Run server application unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Create blank .env file for testing purposes
        run: touch .env

      - name: Run unit tests
        run: npm run test:ci
